FROM php:8.4-fpm

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql mysqli

# (Opcional) Instalar extensiones adicionales que puedas necesitar
# RUN docker-php-ext-install bcmath intl
